-- MySQL Script generated by MySQL Workbench
-- 04/21/20 23:27:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Hostle_Management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hostle_Management` ;

-- -----------------------------------------------------
-- Schema Hostle_Management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hostle_Management` DEFAULT CHARACTER SET utf8 ;
USE `Hostle_Management` ;

-- -----------------------------------------------------
-- Table `Hostle_Management`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Student` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Student` (
  `Student_ID` VARCHAR(9) NOT NULL,
  `First_Name` VARCHAR(50) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Room_Number` VARCHAR(10) NOT NULL,
  `Block` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_ID`),
  UNIQUE INDEX `Student_id_UNIQUE` (`Student_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Staff` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Staff` (
  `Staff_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Mobile_number` INT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Staff_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Hostel_Block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Hostel_Block` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Hostel_Block` (
  `Block_name` VARCHAR(10) NOT NULL,
  `Student_Student_id` VARCHAR(9) NOT NULL,
  `Staff_Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Block_name`),
  UNIQUE INDEX `Block_name_UNIQUE` (`Block_name` ASC),
  INDEX `fk_Hostel_Block_Student_idx` (`Student_Student_id` ASC),
  INDEX `fk_Hostel_Block_Staff1_idx` (`Staff_Staff_ID` ASC),
  CONSTRAINT `fk_Hostel_Block_Student`
    FOREIGN KEY (`Student_Student_id`)
    REFERENCES `Hostle_Management`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hostel_Block_Staff1`
    FOREIGN KEY (`Staff_Staff_ID`)
    REFERENCES `Hostle_Management`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Leave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Leave` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Leave` (
  `Leave_ID` INT NOT NULL AUTO_INCREMENT,
  `Student_Student_ID` VARCHAR(9) NOT NULL,
  `Leave_Date` DATETIME NOT NULL,
  `Return_Date` DATETIME NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Leave_ID`),
  INDEX `fk_Leave_Student1_idx` (`Student_Student_ID` ASC),
  CONSTRAINT `fk_Leave_Student1`
    FOREIGN KEY (`Student_Student_ID`)
    REFERENCES `Hostle_Management`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Attendance` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Attendance` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Student_Student_ID` VARCHAR(9) NOT NULL,
  `Attendence` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Attendance_Student1_idx` (`Student_Student_ID` ASC),
  CONSTRAINT `fk_Attendance_Student1`
    FOREIGN KEY (`Student_Student_ID`)
    REFERENCES `Hostle_Management`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Grievances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Grievances` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Grievances` (
  `Grievances_ID` INT NOT NULL AUTO_INCREMENT,
  `Student_Student_ID` VARCHAR(9) NOT NULL,
  `Grievances` VARCHAR(200) NOT NULL,
  `Report_Date` DATETIME NOT NULL,
  PRIMARY KEY (`Grievances_ID`),
  INDEX `fk_Grievances_Student1_idx` (`Student_Student_ID` ASC),
  CONSTRAINT `fk_Grievances_Student1`
    FOREIGN KEY (`Student_Student_ID`)
    REFERENCES `Hostle_Management`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Visitors` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Visitors` (
  `Visitor_ID` INT NOT NULL AUTO_INCREMENT,
  `Purpose` VARCHAR(100) NOT NULL,
  `Visit_Date` DATETIME NOT NULL,
  PRIMARY KEY (`Visitor_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Student_has_Visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Student_has_Visitors` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Student_has_Visitors` (
  `Student_Student_id` VARCHAR(9) NOT NULL,
  `Visitors_Visitor_ID` INT NOT NULL,
  PRIMARY KEY (`Student_Student_id`, `Visitors_Visitor_ID`),
  INDEX `fk_Student_has_Visitors_Visitors1_idx` (`Visitors_Visitor_ID` ASC),
  INDEX `fk_Student_has_Visitors_Student1_idx` (`Student_Student_id` ASC),
  CONSTRAINT `fk_Student_has_Visitors_Student1`
    FOREIGN KEY (`Student_Student_id`)
    REFERENCES `Hostle_Management`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Visitors_Visitors1`
    FOREIGN KEY (`Visitors_Visitor_ID`)
    REFERENCES `Hostle_Management`.`Visitors` (`Visitor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hostle_Management`.`Shifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hostle_Management`.`Shifts` ;

CREATE TABLE IF NOT EXISTS `Hostle_Management`.`Shifts` (
  `Staff_Staff_ID` INT NOT NULL,
  `Shifts_ID` INT NOT NULL AUTO_INCREMENT,
  `Entry_Time` DATETIME NULL,
  `Exit_Time` DATETIME NULL,
  PRIMARY KEY (`Staff_Staff_ID`, `Shifts_ID`),
  INDEX `fk_Shifts_Staff1_idx` (`Staff_Staff_ID` ASC),
  CONSTRAINT `fk_Shifts_Staff1`
    FOREIGN KEY (`Staff_Staff_ID`)
    REFERENCES `Hostle_Management`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
